print("Hello, World!")
print("Python is fun!")
print(3 + 4)
print("The result of 5 * 7 is", 5 * 7)
print("My name is John.")
print("This is a string with a newline character\nthat breaks into two lines.")
print("This is a string with a tab character:\tseparated by a tab.")
print("He said, 'Python is awesome!'")
print('She replied, "Indeed it is!"')
print("The value of pi is approximately", 3.14159)
print("The weather today is sunny.")
print("Today's date is", "July 24, 2024")
print("I have", 3, "apples.")
print("The square of 9 is", 9 ** 2)
print("Python " + "concatenates " + "strings.")
print("The list of numbers is", [1, 2, 3, 4, 5])
print("The dictionary is", {"name": "Alice", "age": 30})
print("100 in binary is", bin(100))
print("3.14 in scientific notation is", format(3.14, ".2e"))
print("The temperature is", 25, "degrees Celsius.")

