name: test-action-on-flag
on:
    push:
        branches:
        - main

jobs:
    stage:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.1.7
        - name: Set up python
          uses: actions/setup-python@v5.1.1
          with:
            python-version: 3.9
        - name: Run Test2
          run: |
              python test2.py
            
